stages:
  - update
  - test
  - deploy

update_repo:
  stage: update
  only:
    - dev
  script:
    - cd /media/sf_dev/consulwar/ && git fetch git@gitlab.consulwar.ru:zav/consulwar.git && git checkout dev && git reset --hard dev && git pull

run_jshint:
  stage: test
  script:
    - jshint *

job_deploy:
  stage: deploy
  only:
    - dev
  script:
    - cd /media/sf_dev/consulwar/ && sudo mupx deploy